// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuGFepkNdTLU-kbwG7T-UGl9yNI9nKUg',
    appId: '1:683830123184:android:14df9cfeb72769e1fd7975',
    messagingSenderId: '683830123184',
    projectId: 'dongnesosik',
    storageBucket: 'dongnesosik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7MfjrpZzlQu7vzp_jVQqz07bm23bsc7s',
    appId: '1:683830123184:ios:78dbba129907da67fd7975',
    messagingSenderId: '683830123184',
    projectId: 'dongnesosik',
    storageBucket: 'dongnesosik.appspot.com',
    androidClientId: '683830123184-5vlgrji7tpdd5sv6fcvii7fbdcpnrj9n.apps.googleusercontent.com',
    iosClientId: '683830123184-5ivu6t20qf02aa9j10eq7miceiq6ncpd.apps.googleusercontent.com',
    iosBundleId: 'com.jj.dongnesosik.dev',
  );
}
