// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3gr2I5etPCmYY1-otR745jSo95_YVDoY',
    appId: '1:558531435873:web:7d175d89050406793e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    authDomain: 'dongnemento.firebaseapp.com',
    storageBucket: 'dongnemento.appspot.com',
    measurementId: 'G-0ECG5D3GNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcA4p5KxOzlu-8mNCwfqIohixj7WcSchk',
    appId: '1:558531435873:android:d5272691fb3f29a13e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    storageBucket: 'dongnemento.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsGUUmGc6J86ZMxV6EDqqjHwaS89AJpc',
    appId: '1:558531435873:ios:773b7e9fd920a9643e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    storageBucket: 'dongnemento.appspot.com',
    iosClientId: '558531435873-i2q84oifhovsn6omc920ijmttm0kocjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsGUUmGc6J86ZMxV6EDqqjHwaS89AJpc',
    appId: '1:558531435873:ios:773b7e9fd920a9643e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    storageBucket: 'dongnemento.appspot.com',
    iosClientId: '558531435873-i2q84oifhovsn6omc920ijmttm0kocjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseProject',
  );
}
