// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcA4p5KxOzlu-8mNCwfqIohixj7WcSchk',
    appId: '1:558531435873:android:98f645c6d57a43c03e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    storageBucket: 'dongnemento.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsGUUmGc6J86ZMxV6EDqqjHwaS89AJpc',
    appId: '1:558531435873:ios:6add402ffafbef483e7920',
    messagingSenderId: '558531435873',
    projectId: 'dongnemento',
    storageBucket: 'dongnemento.appspot.com',
    androidClientId: '558531435873-p9idq74bnj2puae4tnm5bn3t20cpqn7j.apps.googleusercontent.com',
    iosClientId: '558531435873-c3vnd6rn1taslfmemcu2cjidjorfqbh8.apps.googleusercontent.com',
    iosBundleId: 'com.jtb.dongnemento.dev',
  );
}
