/// Flutter icons DUIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DUIcons
///      fonts:
///       - asset: fonts/DUIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class DUIcons {
  DUIcons._();

  static const _kFontFam = 'DUIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_s = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_default = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_sel = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_thumb_alram = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_n = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_s = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_forward_s = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_forward = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_s = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData default_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData del = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_less_s = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_less = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_more_s = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_more = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goout = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_default = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_sel = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invitation = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_default = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_sel = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manage_default = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manage_sel = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_default = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_move = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_sel = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_default = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_sel = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_default = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_sel = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notice = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prev = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qna = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_n = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_s = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_small = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notice_master = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_master = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_alram_on = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_alram_mute = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_sel_1 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_list = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingdong_del = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compact_down = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData msg_send = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingdong_add = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingdong_close = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData provision = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hyphen = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_s = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fav_sel = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fav = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData postbox_default = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData postbox_selt = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonebook = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_invite = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attend = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_view_on = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_view = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_re = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
