# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)


platform :android do
  desc "firebase deploy"
  lane :fb_distribution do
    sh("cd","..")
    sh("flutter", "build", "apk", "--flavor","prod", "-t", "lib/env/prod.dart")

    firebase_app_distribution(
      app: "1:558531435873:android:dfd6beca9b5db65e3e7920",
      apk_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk"
    )
  end


  desc "playstore_internal"
  lane :ps_internal do
    sh("cd","..")
    sh("flutter", "build", "appbundle", "--flavor","prod", "-t", "lib/env/prod.dart")

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab", 
      track: "internal"
    )
  end
end


