# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#dev 빌드 : fastlane beta --env dev
#prod 빌드 : fastlane release --env prod

default_platform(:android)


platform :android do
  desc "firebase deploy"
  lane :beta do
    sh("cd","..")
    sh("flutter", "build", "apk", "--flavor","prod", "-t", "lib/env/prod.dart")

    firebase_app_distribution(
      app: "1:558531435873:android:dfd6beca9b5db65e3e7920",
      apk_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk"
    )
  end


  desc "playstore_internal"
  lane :prod do

    # Build app
    flutter_build_android

    version = get_properties_value(
      key: "flutter.versionName",
      path: "local.properties"
    )
    build = get_properties_value(
      key: "flutter.versionCode",
      path: "local.properties"
    )

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab", 
      track: "internal"
    )
  end

  # Flutter build Android
  lane :flutter_build_android do
    puts "flutter clean"
    sh("flutter clean")
    
    puts "cd .."
    sh("cd", "..")

    puts "Flutter build Android"

    sh("flutter", "build", "appbundle", "-t", 'lib/main_prod.dart')
  end
end


