# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#dev 빌드 : fastlane beta --env dev
#prod 빌드 : fastlane release --env prod

default_platform(:android)


platform :android do
  desc "firebase deploy"
  lane :beta do
    sh("cd","..")
    sh("flutter", "build", "apk", "--flavor","prod", "-t", "lib/env/prod.dart")

    firebase_app_distribution(
      app: "1:558531435873:android:dfd6beca9b5db65e3e7920",
      apk_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk"
    )
  end


  desc "playstore_internal"
  lane :prod do

    # Send slack message
    before_send_slack_message(msg: "💫 Android TestFlight 배포를 시작합니다.")

    # Build app
    flutter_build_android

    version = get_properties_value(
      key: "flutter.versionName",
      path: "local.properties"
    )
    build = get_properties_value(
      key: "flutter.versionCode",
      path: "local.properties"
    )

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab", 
      track: "internal"
    )

    # Send slack message
    after_send_slack_message(msg: "🚀 Successfully distributed a new beta build ✨")
  end

  # Flutter build Android
  lane :flutter_build_android do
    puts "flutter clean"
    sh("flutter clean")
    
    puts "cd .."
    sh("cd", "..")

    puts "Flutter build Android"

    sh("flutter", "build", "appbundle", "-t", 'lib/main_prod.dart')
  end


 # Before Send slack message
 lane :before_send_slack_message do |options|
  yaml_file_path = "../../pubspec.yaml"
  data = YAML.load_file(yaml_file_path)
  version = data["version"].split("+")[0]
  build_number = data["version"].split("+")[1]
  slack(
    message: options[:msg],
    payload: {
      "Version" => version,
      "Build" => build_number,
      "Environment" => "#{ENV['ENV_EMOJI']} #{ENV['ENV']}"
    },
  )
end

   # After Send slack message
   lane :after_send_slack_message do |options|
    version = get_properties_value(
      key: "flutter.versionName",
      path: "local.properties"
    )
    build = get_properties_value(
      key: "flutter.versionCode",
      path: "local.properties"
    )
    slack(
      message: options[:msg],
      # channel: "#channel",
      payload: {
        "Version" => version,
        "Build" => build,
        "Environment" => "#{ENV['ENV_EMOJI']} #{ENV['ENV']}"
      },
    )
  end
end


